---
- name: Configure Ubuntu Web Server
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    app_user: "webapp"
    app_dir: "/var/www/html"
    domain_name: "example.com"

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install necessary packages
      apt:
        name:
          - nginx
          - python3-pip
          - git
          - curl
          - unzip
          - ufw
        state: present
        update_cache: yes

    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        shell: /bin/bash

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"

    - name: Copy sample index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Terraform + Ansible Deployment</title>
              <style>
                  body { 
                      font-family: Arial, sans-serif; 
                      max-width: 800px; 
                      margin: 50px auto; 
                      padding: 20px; 
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                  }
                  .container { 
                      background: rgba(255,255,255,0.1); 
                      padding: 30px; 
                      border-radius: 15px; 
                      backdrop-filter: blur(10px);
                  }
                  h1 { color: #fff; text-align: center; }
                  .success { color: #4CAF50; font-weight: bold; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🚀 Deployment Successful!</h1>
                  <p class="success">Your server was deployed using Terraform and Ansible!</p>
                  <p><strong>Instance IP:</strong> {{ ansible_host }}</p>
                  <p><strong>Server:</strong> {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
                  <p><strong>Date:</strong> {{ ansible_date_time.iso8601 }}</p>
                  <p>This page was automatically deployed using Infrastructure as Code principles.</p>
              </div>
          </body>
          </html>
        dest: "{{ app_dir }}/index.html"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0644"

    - name: Configure nginx
      template:
        src: "templates/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/default"
      notify: restart nginx

    - name: Enable and start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 80
        - 443
      notify: reload ufw

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny

    - name: Display deployment info
      debug:
        msg: "Deployment completed! Server is available at http://{{ ansible_host }}"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: reload ufw
      command: ufw reload
