- name: Create app directory
  file:
    path: /app
    state: directory
    mode: "0755"

- name: Copy docker-compose file
  template:
    src: ../../templates/docker-compose.prod.yml.j2
    dest: /app/docker-compose.yml

- name: Login to Docker Hub
  shell: |
    echo "{{ dockerhub_token }}" | docker login -u "{{ dockerhub_username }}" --password-stdin

- name: Pull and start containers
  shell: |
    cd /app && docker compose pull
    cd /app && docker compose up -d --remove-orphans

- name: Check containers status
  shell: docker ps
  register: container_status

- name: Show containers status
  debug:
    msg: "{{ container_status.stdout }}"
