- name: Deploy application to production
  hosts: production
  become: yes
  vars:
    dockerhub_username: "{{ dockerhub_username }}"
    dockerhub_token: "{{ dockerhub_token }}"

  roles:
    - role: docker
    - role: deploy
