---
  - name: Deploy Ecommerce Application
    hosts: all
    become: yes
    vars:
      dockerhub_username: "your_dockerhub_username"
      
    tasks:
      - name: Install Docker
        apt:
          name: docker.io
          state: present
          update_cache: yes
  
      - name: Install Docker Compose
        get_url:
          url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
          dest: /usr/local/bin/docker-compose
          mode: '0755'
  
      - name: Login to Docker Hub
        community.docker.docker_login:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        when: dockerhub_password is defined
  
      - name: Create application directory
        file:
          path: /opt/ecommerce
          state: directory
  
      - name: Copy docker-compose.yml
        copy:
          src: docker-compose.yml
          dest: /opt/ecommerce/docker-compose.yml
  
      - name: Pull and run containers
        community.docker.docker_compose:
          project_src: /opt/ecommerce
          pull: yes
          build: no
          restarted: yes