name: Deploy to Production

on:
  workflow_run:
    workflows: ["NestJS Server CI", "React Client CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # Запускаем только если both workflow успешны И это push в main
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main # Всегда используем main ветку для деплоя

      - name: Setup Ansible with Docker collection
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Create SSH private key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Run Ansible playbook (with high verbosity for debugging)
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          # Используем -vvv для максимальной детализации в логах, что поможет
          # при диагностике проблем с SSH (например, Permission denied)
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml \
            --private-key ./private_key \
            -e "dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}" \
            -e "dockerhub_token=${{ secrets.DOCKERHUB_TOKEN }}" \
            -e "ansible_host=${{ secrets.SERVER_IP }}" \
            -vvv
