name: Deploy to Production

on:
  workflow_run:
    workflows: ["Server CI", "Client CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml \
            --private-key <(echo "${{ secrets.SSH_PRIVATE_KEY }}") \
            -e "secrets.DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" \
            -e "secrets.DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
